preload = /home/coni/Pictures/wallpaper.jpg
preload = /home/coni/Pictures/delftware.jpg
wallpaper = eDP-1,/home/coni/Pictures/wallpaper.jpg
wallpaper = DP-1,/home/coni/Pictures/wallpaper.jpg
wallpaper = HDMI-A-1,/home/coni/Pictures/wallpaper.jpg
