preload = /home/coni/Pictures/wallpaper.jpg
preload = /home/coni/Pictures/delftware.jpg
preload = /home/coni/Pictures/samurai-champloo.png
wallpaper = eDP-1,/home/coni/Pictures/samurai-champloo.png
wallpaper = DP-1,/home/coni/Pictures/chateau-ambulant.png
wallpaper = HDMI-A-1,/home/coni/Pictures/samurai-champloo.png
splash = false
