#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-1 --mode 1920x1080 --primary
xrandr --output DVI-I-0 --mode 1680x1050 --noprimary

bspc monitor HDMI-1 -d I II III IV V
bspc monitor DVI-I-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 30

xsetroot -cursor_name left_ptr & 


nitrogen --restore
setxkbmap fr
setxkbmap -option grp:alt_shift_toggle fr,us &

bash $HOME/.config/polybar/launch.sh

picom --config ~/.config/picom/picom.conf